-- geelato-mail 邮件本地读模型表（最终结构 = fms V122 建表 + V125 bu/dept + V126 标签/草稿扩展 + V127 发送/撤回状态 + V133 in_reply_to）
-- 幂等：由 MailSchemaInitializer 不存在该表时执行（落位跟随 ORM 路由，缺省主库）

CREATE TABLE IF NOT EXISTS `mail_message` (
  `id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键（雪花ID，响应层转number返回前端）',
  `account_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '所属邮箱账户ID（mail_account.id）',
  `user_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '所属用户ID（冗余，便于隔离查询）',
  `message_id` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'RFC Message-ID',
  `in_reply_to` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'RFC In-Reply-To 头（父邮件 Message-ID；无则回退 References 链末位）',
  `imap_uid` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'IMAP UID（同步去重依据，与folder联合同步）',
  `folder` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'inbox' COMMENT '文件夹（inbox/sent/drafts/trash/spam/archive/custom:{id}）',
  `subject` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '主题',
  `from_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '发件人显示名',
  `from_email` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '发件人地址',
  `to_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '收件人JSON数组 [{name,email}]',
  `cc_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '抄送JSON数组',
  `bcc_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '密送JSON数组',
  `preview` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '列表预览文本（正文摘要）',
  `content_html` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT 'HTML正文',
  `content_text` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '纯文本正文',
  `send_date` datetime NOT NULL COMMENT '邮件日期（发送/接收时间）',
  `read_status` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'unread' COMMENT '已读状态（read/unread）',
  `flags_json` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '[]' COMMENT '标记JSON数组（starred/todo/done 等）',
  `mail_size` int NOT NULL DEFAULT 0 COMMENT '邮件大小（字节）',
  `has_attachment` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否含附件',
  `attachments_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '附件元数据JSON数组 [{name,size,contentType,url}]',
  `label_ids` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '[]' COMMENT '标签ID JSON数组（邮件-标签关联）',
  `note` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户备注',
  `priority` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'normal' COMMENT '优先级（high/normal/low）',
  `is_draft` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否草稿',
  `draft_ext_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '草稿扩展字段JSON（写信页恢复用）',
  `send_status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '发送状态（queued/sending/sent/failed；仅发件箱副本有值）',
  `send_error` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '发送失败原因（SMTP 错误摘要）',
  `withdraw_status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '撤回状态（failed；SMTP 不支持真实撤回，withdrawn 预留给服务商级能力）',
  `seq_no` int NULL DEFAULT 0 COMMENT '排序',
  `tenant_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '租户编码',
  `dept_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '部门',
  `bu_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '单位',
  `del_status` int NOT NULL DEFAULT 0 COMMENT '逻辑删除状态，1：已删除、0：未删除',
  `update_at` datetime NOT NULL COMMENT '更新时间',
  `updater` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '更新者',
  `updater_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '更新者名称',
  `create_at` datetime NOT NULL COMMENT '创建时间',
  `creator` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '创建者',
  `creator_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '创建者名称',
  `delete_at` datetime NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_account_folder_uid` (`account_id` ASC, `folder` ASC, `imap_uid` ASC) USING BTREE COMMENT 'IMAP同步去重',
  INDEX `idx_user_folder_date` (`user_id` ASC, `folder` ASC, `del_status` ASC, `send_date` DESC) USING BTREE COMMENT '列表查询主索引',
  INDEX `idx_tenant_status` (`tenant_code` ASC, `del_status` ASC) USING BTREE,
  INDEX `idx_message_id` (`message_id` ASC) USING BTREE,
  INDEX `idx_in_reply_to` (`in_reply_to` ASC) USING BTREE COMMENT '按父邮件反查子回复（会话归组）'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '邮件本地读模型表（IMAP同步落库，SMTP发送副本）' ROW_FORMAT = Dynamic;
