## Participant structured resolution
integration.declaration.participant-resolution.store-file=${GEELATO_INTEGRATION_PARTICIPANT_RESOLUTION_STORE_FILE:${user.dir}/data/participant-resolution-store.json}

## libpostal runtime
integration.declaration.participant-resolution.libpostal.data-dir=${GEELATO_INTEGRATION_LIBPOSTAL_DATA_DIR:/data/libpostal/libpostal}
integration.declaration.participant-resolution.libpostal.library-file=${GEELATO_INTEGRATION_LIBPOSTAL_LIBRARY_FILE:}
integration.declaration.participant-resolution.libpostal.download-data-if-needed=${GEELATO_INTEGRATION_LIBPOSTAL_DOWNLOAD_DATA_IF_NEEDED:false}
integration.declaration.participant-resolution.libpostal.senzing=${GEELATO_INTEGRATION_LIBPOSTAL_SENZING:true}