sentry.dsn=https://c88a7651f03065db1a5ffb2863a1db8e@o4511391949586432.ingest.us.sentry.io/4511425734443008
# Add data like request headers and IP for users,
# see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
sentry.send-default-pii=true
# Enable sending logs to Sentry
sentry.logs.enabled=true
# Set traces-sample-rate to 1.0 to capture 100% of transactions for tracing.
# We recommend adjusting this value in production.
sentry.traces-sample-rate=1.0
# Set profile-session-sample-rate to 1.0 to profile 100% of profile sessions.
sentry.profile-session-sample-rate=1.0
# Set profile-lifecycle to trace to automatically start and stop
# profiling when a transaction starts and finishes.
sentry.profile-lifecycle=TRACE