name: Deploy to Test
on:
  push:
    branches:
      - master

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook
        run: |
          curl \
            --header "Content-Type: application/json" \
            --request POST \
            --data "{\"GEELATO_PUSH_TOKEN\":\"${{ secrets.GEELATO_PUSH_TOKEN }}\"}" \
            http://flow-openapi.aliyun.com/scm/webhook/wgXnhEJupbRO7xep2gGO
